### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#1]
# Value Proposition
As a user
I would like to see a list of yoga exercises
So that I have an overview or an inspiration of my possible Daily Sequence.
# Description

![Image](https://user-images.githubusercontent.com/107836739/184610616-20ddc21f-a35f-4eaa-8596-54829048d1cb.png)

# Acceptance Criteria

- [x] a headline is Displayed
- [x] a list of Yoga Exercises

# Tasks

(for developers team)

- [x] create a new branch 
- [x] create card Component
- [x] create a array - list 

# Complexity
M

**Comment by RobertBReich** [comment]
3te Acceptance Criteria ist buggy.
Es sind keine Tasks definiert.

**Comment by Mersag** [comment]
Thank you.Acceptance step by Step and I add some Task .

**Comment by RobertBReich** [comment]
Hey Meral,

looks better, but there are still some empty "- [ ]" in AC and Tasks. 
Found a typo in the headline: "so that can I add" should be "so that I can add". 
Those texts: "Scribble / design or text" and "(for developers team)" can be removed when you put in your own text.

cheers
R.

**Comment by Mersag** [comment]
Hey Robert, 

thank you for your feedback. I optimized it.

**Comment by RobertBReich** [comment]
Hey Meral,

looks good. 😎

**Comment by Mersag** [comment]
Nice. Thank You

**Comment by JessicaLoers** [comment]
**Hi @Mersag **
I really like the idea of your App. 🫶

I have a few more suggestions, not to make life difficult for you, but rather as an exercise to make it easier and easier for you to write further user stories.

**Value Proposition**
- To make it easier for us as developers to read, I would recommend break the Value Proportion in different lines.
- In this feature it's actually only possible to see single exercises as an overview/list. For this reason, I would leave out add/choose. A desired user value could be to have inspiration for the daily sequence, for example. 
> As a user, I would like to see a list of yoga exercises so that I can add(choose) to my Daily Sequence.

**As a user**
**I would like** to see a list of yoga exercises
**So that I have** an overview or an inspiration of my possible Daily Sequence

**Acceptance Criteria** - this describes different scenarios from the user's perspective, with possible user interaction - even if you don't really have interactions in this feature / user story yet, but that's no problem for now 😉

> add a card for Asana image
 add a headline
 
 - a headline with the yoga (asana) lexicon
 - different yoga exercises are displayed

If you have any questions, feel free to ask.

**Comment by Mersag** [comment]
Hi Jessica , 
so thank you for the Constructive feedback, it makes sens. I will consider. It makes sense because the Array or list is the first Step -Value .

**Comment by JessicaLoers** [comment]
**Hi @Mersag** 

great and almost done 🎉

Let's try something out and mentally and literally 😁 add the "of user" to the term "acceptance criteria"
**=> acceptance criteria (of the user)**
 You notice that the verb `add` no longer fits here, because the `users don't add the headline`, `they expect the headline`
 
 Long story short, I would like to recommend you to change the term add  with a term like is displayed or something like that. 🙂
