### ISSUE TITLE
User Story 5 Add all Yoga images

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#11]
# Value Proposition

Als Nutzer,
möchte ich Bilder zu den einzelnen Yoga Asana Namen sehen,
damit ich die Asana(Übung) besser verstehe.

# Description

![Image](https://user-images.githubusercontent.com/107836739/187081090-34619fad-012c-4d25-a661-375757d42175.png)

# Acceptance Criteria

- [ ] Zur jeder Übung ein Bild 
- [ ] Liste von 12 Yoga Grundübungen 

# Tasks

- [ ] neuen branch erstellen 
- [ ] basic styled component

# Complexity

S
