### ISSUE TITLE
User Story 7 Styling

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#13]
# Value Proposition

Als Nutzer 
möchte ich eine gestylte App Oberfläche,
damit ich eine bessere Benutzererfahrung habe.

# Description

Ein einheitliches Styling 

# Acceptance Criteria

- [ ] die App, wird einen einheitlichen Styling erhalten 
- [ ] das Format der App passt sich dem iPhone SE an 

# Tasks

- [ ] neuen branch erstellen 
- [ ] statt add to Routine ein Icon nutzen
- [ ] statt delete ein Icon nutzen
- [ ] Link Wirkung Stylen
- [ ] den Elementen Styling hinzufügen 
- [ ] styled component nutzen 

# Complexity

 L
