### ISSUE TITLE
User Story 2

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#2]
# Value Proposition

As a user
I want to have detailed information about the exercise effects
So that I'm able to choose the Daily Sequence I need today
# Description

![Image](https://user-images.githubusercontent.com/107836739/185093809-1e5c6204-97ef-4fe0-9522-63568ae9327a.png)

# Acceptance Criteria
- [x] by clicking on the effect button, the effect page opens
- [x] The exercise's Title is displayed on top
- [ ] exercise image, so the user can visualize the Exercise
- [ ] effect button in the card for detail Information about Effect 
- [x] Categories like (physical, mental, energetics, chakra)are displayed on the Effect Page 
- [x] go back button, so the user is redirected to the exercises overview

# Tasks
 - [ ]  a link to redirect to the effect page
 - [x]  a link to redirect to the home page   
 - [x]  implement useRouter
 - [x]  component/ Page effect

# Complexity

M

**Comment by tsimvris** [comment]
- was meinst du mit "clear communicate what to do Ui-Ux"

- Die tasks fehlen

**Comment by Mersag** [comment]
Ok . Danke . Ich habe Task eingefügt .

**Comment by RobertBReich** [comment]
Hi Meral,

now everything looks cool, except that you killed all [ ] in front of the tasks. 😄
Those convert into checkboxes, that you want to have to click stuff that you have finished.

other then that it looks good.

cheers
R.

**Comment by Mersag** [comment]
Oh ,NO. I optimized it. Thank you

**Comment by JessicaLoers** [comment]
**Hi @Mersag** -  it's me again 😁

I just noticed one general thing. Your project board is probably set to private - this is the default setting. 
It would be great if you **change the project to public visibility** in the project settings, so that we can take a look at your board. 
Here is a link how to change your setting: [Changing project (classic) visibility](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility)

Regarding your second User Story, I would like to think about the following comments, questions and notes:

**In generell**
Our goal is: `alway have a running app`. Therefore it's important to `avoid placeholder elements and empty pages`. 
In relation to your user story, this little guiding principle means the following: 
- If I understand it right, the effect button has the aim to refer to a new page, or to show detailed informations/effects of the single exercises. But this page (detailed exercise effects) doesn't exist yet, so it would lead the user to an empty page and a bad user experience. 🚨

Two Solution options: 
1. Save this User Story for later and write an additional user story like `exercises detailed/effects page`
2. Implement the `exercises detailed/effects page`  in this User Story. 

`! Please keep in mind to adjust your Description/Wire Frame and User Story Titel. `


 **Value Proposition**
- perhaps you like to add break lines here too

> As a user, I want to add a Yoga Asana Effect to see all the effects in a new Page.

- Regarding  my comments above it would make sense to adjust in something like this: 

**As a user**
**I want to** have detailed informations about the exercise effects
**So that I'm**  able to choose the Daily Sequence I need today


**Acceptance Criteria** example if you implement the `exercises detailed/effects page` in this User Story
- and this is where the button comes into "play" 😉  
   - By clicking on the `effect button` the detailed informations about the effects are displayed
   - Detailed informations, categories like "feel good" are displayed
   - The exercises Title is displayed on top
   - By clicking on the `go back button` the user is redirect to the exercises overview/home page
   -  ... 
   
   **Tasks**  example that needs to be adjust. 
   - implement Routing
   - create exercises detailed/effects page
   - ... 
   
Sorry, for this is bunch of input. 🫣

**Comment by Mersag** [comment]
Good morning Jessica,
Step 1
It´s ok. This is the Process of learning, and I am so thankfully for your feedback.:-)
- Project board is now "Public" ( done )

**Comment by Mersag** [comment]
Step 2
- Value proposition is changed. (done)

**Comment by Mersag** [comment]
Step 3

- **Acceptance** and **Task** is optimized. (done )


Dear Jessica, if you have time today, please tell me because I would like to ask something about user Stories.

**Comment by Gw3i** [comment]
Hello @Mersag,
I would recommend to implement all suggestions from @JessicaLoers and post it for a review afterwards 🙂

**Comment by Mersag** [comment]
So ,I Update my User Story 2 ...

**Comment by RobertBReich** [comment]
Hi Meral,

Wasn't this chat history for your first user story or does this board work like this? 
I'm a little confused. 🤔
I'm pretty sure my comment 2 days ago was for a different story.
