### ISSUE TITLE
User Story 3 Asana Routine

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#4]
# Value Proposition
Als Nutzer 
möchte ich meine einzelnen Yoga Asanas auswählen ,
damit ich mir meine tägliche Asana Routine zusammenstellen kann. 
# Description

![Image](https://user-images.githubusercontent.com/107836739/186470940-b230438a-e46d-48a3-98d2-b499fd893661.png)

# Acceptance Criteria
- [x] a page of Asana routine
- [x] a headline to see the name of the page
- [x] a List of selected Asana card 
- [x]  link to the Asana routine Page is displayed

# Tasks
- [x] a new branch 
- [x] a headline Asana routine 
- [x] Component Asana routine
- [x] a list of Asana
- [x] add a link to Page Asana routine 
- [x] a link to Page Asana routine 

# Complexity

 L

**Comment by UniversalTraveller** [comment]
Hi Meral! This looks good. I have a few suggestions though:

- Maybe make the user story smaller. For a start, you could just list the exercises. No need for a delete button.
- You could give the user story a more telling name, like "Exercise List".
- Shouldn't the go back button be part of the acceptance criteria?
- What exactly is part of an exercise? What gets displayed? Just the name?
- There is a bit of template text left in the description.
- Your uppercase letters are going wild. ;-) Rule of thumb: no uppercase letters in the middle of a sentence, except in headlines.

**Comment by Mersag** [comment]
Hi Andreas, thank you for your feedback :-)I implemented your useful points.

**Comment by UniversalTraveller** [comment]
Okay, cool! The template text under the scribble ("Scribble / design or text") is still there. Maybe delete it?

I think the headline on the page in your app was a misunderstanding. I meant the user story here on Github could have a name like "Exercise List" instead of "User Storie 3".

**Comment by Mersag** [comment]
Hey Andreas, thank you again for your useful feedback. I delete the Text("Scribble / design or text"). About the "user Story3"Name your feedback is very usefully and at the moment it is for me easy to see the steps that I Go whiteout chaos.As soon as I feel a bit more confident, I will consider your feedback. :-)

**Comment by JessicaLoers** [comment]
**Hi @Mersag**  🙂

You want to display a list of favorite exercises, right?
But how and where can the user mark the exercise as my favorite?

I'm afraid that you have forgotten one step  "Mark exercise as favorite" 🫣

**Comment by Mersag** [comment]
Hi Jessica ,

this step is include in User Story 2 as 2add" Button ...

:-)

**Comment by JessicaLoers** [comment]
**Hi @Mersag** ✌️
hmmmm ... 
Let's take look at the misconception/miss-understanding to solve it 🙂  

The Value Proposition of your second user story is: 

> As a user
> I want to have detailed information about the exercise effects
> So that I'm able to choose the Daily Sequence I need today


⬇️
This user story / feature shows detailed information of a single exercise - nothing more, nothing less. 
[Here is the Link to the related User Story](https://github.com/users/Mersag/projects/1)

**Please keep in mind:** each story is a self-contained feature.

**Comment by Mersag** [comment]
Hi Jessica, 

wie cool, dass du das entdeckt hast :-) 

Stimmt genau, das Missverständnis rührt daher, dass ich die Überschriften anders verwendet habe, statt **"Daily Sequenz"** habe ich **"Exercise List"** verwendet. 
Jetzt habe ich mein Deskription optimiert und nun müsste es passen.

**Comment by Mersag** [comment]
Hi Jessica, 
ich habe nach unserem Gespräch, einige Punkte optimiert und unter Deskription eine aktuelle Version hinzugefügt. Die neue Version habe ich dir auf Slack zum Schauen gesendet.SoSoSoSoSoSo danke für dein Feedback :-)

**Comment by JessicaLoers** [comment]
Diese User Story ist approved, liebe @Mersag 🎉
