### ISSUE TITLE
User Story 4 Delete Button

### ISSUE THREAD

**Issue by Mersag** [Mersag/capstone-projekt#8]
# Value Proposition

Als Nutzer,
möchte ich einen delete Button in meiner Asana Routine Page sehen,
damit ich weiß, dass eine delete Funktion existiert.

# Description

![Image](https://user-images.githubusercontent.com/107836739/186662557-f26717b5-5d6e-4e33-b3dd-72197965ef99.png)

# Acceptance Criteria

- [ ] eine Übung aus Asana Routine löschen 
- [ ] beim Klicken auf das delete Button, wird die Übung gelöscht

# Tasks

- [ ] neuen branch erstellen
- [ ] delete Button 
- [ ] delete Button zur Asana Routine Übung hinzufügen 

# Complexity

S

**Comment by RobertBReich** [comment]
Hi Meral,
"möchte ich einen delete Button in meiner Asana Routine Page **Übungen** sehen"
Ist das Übungen da nicht über? 
Im Bild einmal Rutine anstelle von Routine, sowie asana und Asana gemixt. Ich würde alles groß schreiben?

Acceptance Criteria 2, Komma hinter Button, nicht vor wird. 😄

Ansonsten: Super 👍
cheers
R.

**Comment by Mersag** [comment]
Hi Robert, 
Thank you for your advice. I optimized it. 
1) Change description
2) Change Value (delete Übung)
3) Acceptance Criteria changed

See you, Thank you :-)

**Comment by RobertBReich** [comment]
Hi Meral,
looks good. 👍

**Comment by Mersag** [comment]
Punkt 1) "add" Button Name auf Page Home und Wirkung wird umgeändert auf "add to routine"
Punkt 2)"zurück" Button wird auf Page Home gelöscht

mit Absprache Petros . Danke
